### PR TITLE
Created Landing Page for Cloudlibz

### PR DESCRIPTION
**Pull request by raghavpuri**
Created a new landing page for cloudlibz,no templates have been used ,screenshots are attached below 
screen shot 2018-01-10 at 2 54 45 am
screen shot 2018-01-10 at 2 54 55 am
screen shot 2018-01-10 at 2 55 02 am
screen shot 2018-01-10 at 2 55 08 am

### CODE REVIEW

**Comment by rehrumesh** [comment]
Check for the comments mentioned in GCI portal

**Comment by rehrumesh** [comment]
Great work so far

**Comment by raghavpuri** [comment]
Made all the necessary changes ,here are the screenshots :)

new1
new2
new3
new4
new5

**Comment by raghavpuri** [comment]
Made edits :)

**Comment by rehrumesh** [comment]
I am reverting this. Due to some issue, CSS isn't loading properly. Please share the setup workflow.
image

**Comment by raghavpuri** [comment]
Yes the address doesn't have the folder, even I checked making edits :)

**Comment by rehrumesh** [comment]
What do you mean?

**Pull request merged**
