### PR TITLE
Landing page for cloudlibz

### PR DESCRIPTION
**Pull request by padamchopra**
I've used a jekyll template for the landing page. Here are the attached screenshots-

cloudlibz1
cloudlibz2
cloudlibz3
cloudlibz4
cloudlibz5
screenshot from 2018-01-06 21-24-12

### CODE REVIEW

**Comment by rehrumesh** [comment]
Hi @padamchopra 

One thing to be added. Cloudlibz unified most of the cloud vendors including AWS, Google cloud, Azure, Rackspace, Openshift etc. Can you add a section with those logos?

**Comment by padamchopra** [comment]
I've implemented the suggestion @rehrumesh , Here's a screenshot of it
screenshot from 2018-01-10 10-48-51

**Comment by rehrumesh** [comment]
Thanks for your efforts in this task. For now, I will close this PR, but I plan to reopen this PR and merge it later.

**Comment by padamchopra** [comment]
Ok @rehrumesh

**Pull request closed without merging**
