### PR TITLE
Complete Website For Cloudlibz including landing page : ) (NOT PART OF GCI)

### PR DESCRIPTION
**Pull request by iammosespaulr**
screenshot from 2018-01-13 23-54-00
screenshot from 2018-01-13 23-53-56
screenshot from 2018-01-13 23-53-51
screenshot from 2018-01-13 23-53-44
screenshot from 2018-01-13 23-53-34
screenshot from 2018-01-13 23-53-24
screenshot from 2018-01-13 23-53-17
screenshot from 2018-01-13 23-53-10
screenshot from 2018-01-13 23-53-09
screenshot from 2018-01-13 23-53-06
screenshot from 2018-01-13 23-53-04
screenshot from 2018-01-13 23-53-00
screenshot from 2018-01-13 23-52-54

### CODE REVIEW

**Comment by iammosespaulr** [comment]
@rehrumesh please , take a look ..

**Comment by rehrumesh** [comment]
Get in touch section should include: 
* gitter links
* mail link
* github link

No need for the team, pricing, pricing faq sections.

Need a section to show all the cloud providers we are aggregating such as:
aws, google, azure, rackspace, openstack, digitalocean

**Comment by rehrumesh** [comment]
Remove node_modules. add it to gitignore

**Comment by iammosespaulr** [comment]
Sure .. will do the changes and have them uploaded btw thanks for the review ..

**Comment by iammosespaulr** [comment]
@rehrumesh i have done the requested changes .... please review 
ps Here Are some ScreenShots attached ...
screenshot from 2018-01-15 18-08-18
screenshot from 2018-01-15 17-54-14
screenshot from 2018-01-15 17-54-02
screenshot from 2018-01-15 17-42-22

**Comment by iammosespaulr** [comment]
.. Sorry ... i forgot Github and Gmail .. my bad ..

**Comment by iammosespaulr** [comment]
@rehrumesh I have made the changes
screenshot from 2018-01-15 18-20-39

**Comment by iammosespaulr** [comment]
@rehrumesh DONE ... please review
@charithccmc Please review as well

**Comment by rehrumesh** [comment]
Thanks for your GCI efforts

**Pull request closed without merging**
